feat: update choose_dtype function to include new types
WilhelmusLab/ice-floe-tracker-pipeline pull request #169
Opened 2024-10-24 22:06 UTC by hollandjg

Add UInt64 and UInt128, which may be required for the updated pipeline.

Drive-by improvements: 
- make it more obvious that the function is doing what it's meant to do.
- add new testcases
- throw an error if the number can't be represented by any of the types

2024-10-25 17:20 UTC, cpaniaguam requested changes
One suggestion. Thanks!

2024-10-25 17:20 UTC, cpaniaguam commented on test/test-h5.jl
> +    @test_throws "can't be represented" choose_dtype(340_282_366_920_938_463_463_374_607_431_768_211_456)
```suggestion
    @test choose_dtype(BigInt(2)^128 - 1) == UInt128
    @test_throws "can't be represented" choose_dtype(BigInt(2)^128) 
```

2024-10-25 17:20 UTC, cpaniaguam commented on test/test-h5.jl
> +    @test choose_dtype(18_446_744_073_709_551_616) == UInt128
Can 2^64-1 and 2^64 be used here?
```suggestion
    @test choose_dtype(BigInt(2)^64 - 1) == UInt64
    @test choose_dtype(BigInt(2)^64) == UInt128
```

2024-10-25 18:33 UTC, hollandjg commented on test/test-h5.jl
> +    @test_throws "can't be represented" choose_dtype(340_282_366_920_938_463_463_374_607_431_768_211_456)
That's a good idea!

2024-10-28 18:58 UTC, cpaniaguam approved these changes
Thanks!

2024-10-28 20:18 UTC, merged