Jghrefactor/A1-update-dockerfile
WilhelmusLab/ice-floe-tracker-pipeline pull request #174
Opened 2024-10-26 02:08 UTC by hollandjg

2024-11-06 12:01 UTC, tdivoll reviewed
This is great, I think it just need Cylc updates? I'm happy to help with a little guidance to follow the new logic/entrypoint.

2024-11-06 20:53 UTC, cpaniaguam requested changes
Some observations, thanks!

2024-11-06 20:53 UTC, cpaniaguam commented on PythonSetupForIFTPipeline.jl/setup.jl
It seems like this will never be imported into a different file or module. Why not drop the if check and collect the imports at the top? Something like
```julia
#!/usr/bin/env julia

using Conda, etc.

funciton main()
    ...
end

main()

2024-11-06 20:53 UTC, cpaniaguam commented on PythonSetupForIFTPipeline.jl/README.md
In view of this and https://github.com/WilhelmusLab/ice-floe-tracker-pipeline/pull/193#discussion_r1831676246, I think something like a makefile might be useful to simplify all of this.

2024-11-20 19:10 UTC, hollandjg commented on Dockerfile
> +RUN julia --project="/opt/IFTPipeline.jl" -e 'using Pkg; Pkg.rm("IceFloeTracker"); Pkg.add(url="https://github.com/WilhelmusLab/IceFloeTracker.jl", rev="main"); Pkg.instantiate()'
@hollandjg take another look at this.

2024-11-27 14:32 UTC, hollandjg commented on PythonSetupForIFTPipeline.jl/setup.jl
Ah the problem with that is that the `using Pkg; Pkg.instantiate()` has to come before `using Conda`.

I've simplified the file but the imports have to be split across the file.

2024-12-13 18:33 UTC, hollandjg commented on Dockerfile
> +RUN julia --project="/opt/IFTPipeline.jl" -e 'using Pkg; Pkg.rm("IceFloeTracker"); Pkg.add(url="https://github.com/WilhelmusLab/IceFloeTracker.jl", rev="main"); Pkg.instantiate()'
Resolved using a Manifest file in #198

2024-12-17 22:28 UTC, closed without merging