feat(preprocess): add tiling CLI support
WilhelmusLab/ice-floe-tracker-pipeline pull request #207
Opened 2024-12-19 14:45 UTC by hollandjg

2024-12-19 23:51 UTC, cpaniaguam requested changes
Thanks for this! A few things to consider:
- Add support for tiling by tile size
- Extend user-facing documentation about the tiling workflow (histogram equalization, binarization, ice-labeling)
- Move tiling workflow parameters to a configuration file
- Use `-` as separator for cli long options

2024-12-19 23:51 UTC, cpaniaguam commented on IFTPipeline.jl/src/cli.jl
> +        "--tile_rblocks"
Use `-` as separator for cli options for consistency.
```suggestion
        "--tile-rblocks"
```

2024-12-19 23:51 UTC, cpaniaguam commented on IFTPipeline.jl/src/cli.jl
> +        "--tile_cblocks"
```suggestion
        "--tile-cblocks"
```

2024-12-19 23:51 UTC, cpaniaguam commented on IFTPipeline.jl/src/cli.jl
> +        required = false
Have you considered using a configuration file? The CLI is getting quite complex with many options.

2024-12-19 23:51 UTC, cpaniaguam commented on IFTPipeline.jl/src/preprocess.jl
> +    )
```suggestion
    landmask = (
        dilated=.!landmask_dilated,
    )
```

2024-12-19 23:51 UTC, cpaniaguam commented on IFTPipeline.jl/src/preprocess.jl
> +    tile_cblocks=8,
I think @danielmwatkins also wanted some control for tiling by tile size, so another version of this function might be needed for such use case. See [`get_tiles`](https://github.com/WilhelmusLab/IceFloeTracker.jl/blob/a7065e8b987f6349f1c55213deb823cb9b23086d/src/tilingutils.jl#L198).

2024-12-19 23:51 UTC, cpaniaguam commented on IFTPipeline.jl/src/preprocess.jl
> +    )
This is the part that would need to be changed to enable support for tile size. The rest is the same.

2024-12-19 23:51 UTC, cpaniaguam commented on IFTPipeline.jl/src/preprocess.jl
> +    structuring_elements = IceFloeTracker.structuring_elements
Not sure if this would need to be flexible as well. @danielmwatkins, what do you think?

2024-12-19 23:51 UTC, cpaniaguam commented on IFTPipeline.jl/src/preprocess.jl
> +    @debug brighten_factor
This might not be needed.

2024-12-19 23:51 UTC, cpaniaguam commented on IFTPipeline.jl/src/preprocess.jl
> +function preprocess_tiling_single(
Docstring is missing argument descriptions. I am aware they are many which further suggests having a config file is probably a good idea for this use case.

2024-12-19 23:51 UTC, cpaniaguam commented on workflow/rose-suite.conf
> +TILE_CBLOCKS=8
I suppose this also might need some tweaking to enable tiling by tile size.

2024-12-19 23:51 UTC, cpaniaguam commented on IFTPipeline.jl/src/cli.jl
> +        help = "Preprocess truecolor/falsecolor images with tile-based histogram equalization"
The tiling workflow does more than histogram equalization. It also does binarization and ice-water discrimination (ice labeling).

2025-01-07 20:01 UTC, danielmwatkins commented on IFTPipeline.jl/src/preprocess.jl
> +    structuring_elements = IceFloeTracker.structuring_elements
Well, we know that the size and characteristics of the segmentation results are going to be affected by the shapes and sizes of the structuring elements. What might be necessary eventually, since there are so many options, is for my initial work on the calibration to identify the parameters that the results are really sensitive to so that those are the ones accessible from the command line.

2025-01-13 19:47 UTC, hollandjg commented on IFTPipeline.jl/src/preprocess.jl
> +    @debug brighten_factor
It looks totally redundant to me. Not sure why it's there.

2025-01-13 19:49 UTC, hollandjg commented on workflow/rose-suite.conf
> +TILE_CBLOCKS=8
Yes. There can be a separate PR for that – it's too large a change to include here.

2025-01-13 19:50 UTC, hollandjg commented on IFTPipeline.jl/src/preprocess.jl
> +function preprocess_tiling_single(
I think including the argument descriptions here is a good idea.

2025-01-13 19:52 UTC, hollandjg commented on IFTPipeline.jl/src/cli.jl
> +        "--tile_rblocks"
Yes, this needs to be checked for consistency with the parameter names in the cylc file too.

2025-01-13 20:01 UTC, hollandjg commented on IFTPipeline.jl/src/cli.jl
> +        "--tile_cblocks"
Done

2025-01-13 20:04 UTC, hollandjg commented on IFTPipeline.jl/src/preprocess.jl
> +    @debug brighten_factor
Removed pointless assignment, but kept the debug message, so that all the parameters are included in the debug messages.

2025-01-14 15:59 UTC, cpaniaguam commented on IFTPipeline.jl/src/cli.jl
> +        help = "Preprocess truecolor/falsecolor images with tile-based histogram equalization"
The tiling is indeed a significant aspect of the workflow, but there are other important operations beyond histogram equalization within the tiled workflows. To better reflect the full scope of the processing, it would be clearer to either mention these additional operations or reword the line to exclude 'histogram equalization'.

2025-01-14 23:17 UTC, hollandjg commented on IFTPipeline.jl/src/cli.jl
> +        help = "Preprocess truecolor/falsecolor images with tile-based histogram equalization"
Does this cover it?
```
"preprocess_single"
help = "Label ice in a single set of truecolor & falsecolor images"
action = :command

"preprocess_tiling_single"
help = "Label ice in a single set of truecolor & falsecolor images, using histogram equalization"
```

2025-01-14 23:17 UTC, hollandjg commented on IFTPipeline.jl/src/cli.jl
> +        help = "Preprocess truecolor/falsecolor images with tile-based histogram equalization"
Does this cover it?
```
"preprocess_single"  
help = "Label ice in a single set of truecolor & falsecolor images"  
...
"preprocess_tiling_single"  
help = "Label ice in a single set of truecolor & falsecolor images, using histogram equalization"  
```

2025-01-14 23:48 UTC, cpaniaguam commented on IFTPipeline.jl/src/cli.jl
> +        help = "Preprocess truecolor/falsecolor images with tile-based histogram equalization"
I was thinking something more like `"Label ice in a single set of truecolor & falsecolor images using tiled-based processing"`.

2025-01-15 15:23 UTC, hollandjg commented on IFTPipeline.jl/src/cli.jl
> +        help = "Preprocess truecolor/falsecolor images with tile-based histogram equalization"
Great, thanks. Updated.

2025-01-15 15:24 UTC, hollandjg commented on IFTPipeline.jl/src/preprocess.jl
> +function preprocess_tiling_single(
I've added the argument descriptions. What do you think?

2025-01-15 20:22 UTC, cpaniaguam commented on IFTPipeline.jl/src/preprocess.jl
> +function preprocess_tiling_single(
I am not sure I see the new additions. I am looking below here https://github.com/WilhelmusLab/ice-floe-tracker-pipeline/blob/4f70f612673dfe256e550c7a9c3c6a6ee706a33b/IFTPipeline.jl/src/preprocess.jl#L302

2025-01-17 20:56 UTC, hollandjg commented on IFTPipeline.jl/src/preprocess.jl
@cpaniaguam I think you're looking at an earlier commit. Here's the current one.

2025-01-17 20:57 UTC, hollandjg commented on workflow/rose-suite.conf
> +TILE_CBLOCKS=8
We decided on Jan 15th to leave that for another time.

2025-01-17 20:57 UTC, hollandjg commented on IFTPipeline.jl/src/preprocess.jl
> +    tile_cblocks=8,
We decided on Jan 15th to leave that for another time.

2025-01-17 20:57 UTC, hollandjg commented on IFTPipeline.jl/src/preprocess.jl
> +    )
We decided on Jan 15th to leave that for another time.

2025-01-17 21:28 UTC, cpaniaguam approved these changes
lgtm [with comments]

2025-01-17 21:28 UTC, cpaniaguam commented on IFTPipeline.jl/src/cli.jl
> +        # Gamma parameters
```suggestion
        # Gamma adjusting parameters
```

2025-01-17 21:28 UTC, cpaniaguam commented on IFTPipeline.jl/src/preprocess.jl
> +    - `icemask_n_clusters::Int=3`
This is much better, thanks.

2025-01-17 21:28 UTC, cpaniaguam commented on IFTPipeline.jl/src/preprocess.jl
> +    tile_cblocks=8,
Consider adding an issue.

2025-01-24 19:22 UTC, merged