docs(workflow): add how to run non-contiguous dates and case lists
WilhelmusLab/ice-floe-tracker-pipeline pull request #211
Opened 2024-12-19 22:11 UTC by hollandjg

2024-12-19 23:02 UTC, cpaniaguam requested changes
Looks good. One of the scripts could be improved with some annotations.

2024-12-19 23:02 UTC, cpaniaguam commented on workflow/example/util/template.py
Consider annotating `get_fullnames.py` in a similar fashion as this one. I can easily infer what this one script is for thanks to its annotations.

2025-01-07 20:18 UTC, danielmwatkins commented on workflow/README.md
> +cylc tui
At least when I run it, you need to have the name of the run when you call the tui. So something like
```cylc tui your-analysis-run-name```
would be good here.

2025-01-07 20:18 UTC, danielmwatkins commented on workflow/README.md
> +```
this looks really helpful!

2025-01-08 17:53 UTC, danielmwatkins commented on workflow/example/util/template.py
> +        f'--set LOCATION="{r.location}"'
From my test runs, I think that this section of the code is missing a few lines:
```
f'--set START="{r.startdate}" '
f'--set END="{r.enddate}" '
f'--set CENTROID_LAT="{r.center_lat}" '
f'--set CENTROID_LON="{r.center_lon}" '
```
I infer that setting icp and fcp is supposed to adjust the start and end dates, but the SOIT file I get coming out of the run has the dates matching the ones in `workflow/rose-suite.conf'. 

Also, the CSV above needs to have the center lat and lon specified. (As a future note -- this could easily be calculated in another script using pyproj. Seems to me to be something that could be put inside of SOIT.)

For the cases above:
`beaufort-sea-0: center_lon=-135.0, center_lat=75`  
`hudson-bay-0: center_lon=-83.0, center_lat=60`.

2025-01-08 18:00 UTC, danielmwatkins commented on workflow/README.md
> +To loop through a list of cases, you might use a script like this:
It would be helpful to note that the non-specified configuration variables will default to the ones in rose-suite.conf.

2025-01-08 18:40 UTC, danielmwatkins commented on workflow/example/case-list.csv
> +998-beaufort_sea-1200km-20060504-20060506,998,beaufort_sea,1200km,,,-152.9892,67.6236,-114.8220,78.9424,-2334051,-1127689,-414418,757892,2006-05-04,2006-05-06
The 998 and 999 cases at the top here are missing the centroid data, we can just delete them. I'm not sure why the ended up here anyway, it was supposed to be a list of the 100 km cases.

2025-01-13 20:52 UTC, hollandjg commented on workflow/README.md
> +done
I'm not convinced that this will work, because of the way bash requires values to be quoted when passed using a variable. Did you test the change?

2025-01-13 21:00 UTC, hollandjg commented on workflow/example/case-list.csv
> +998-beaufort_sea-1200km-20060504-20060506,998,beaufort_sea,1200km,,,-152.9892,67.6236,-114.8220,78.9424,-2334051,-1127689,-414418,757892,2006-05-04,2006-05-06
Done.

2025-01-13 21:12 UTC, hollandjg commented on workflow/example/util/get_fullnames.py
> +    typer.run(main)
This is a throwaway utility file which shows how you could get a subset of values from a CSV to use when selecting cases from a case list. I've added some rudimentary documentation.

2025-01-13 21:22 UTC, hollandjg commented on workflow/example/util/template.py
> +        f'--set LOCATION="{r.location}"'
Good catch. We need to use `START` and `END` everywhere, as you say – they set the initial and final cycle points, and you can't mix the two definitions.

2025-01-13 21:25 UTC, hollandjg commented on workflow/README.md
> +cylc tui
I'm confused: I don't have to do that at all. When I run `cylc tui`, I see all of the currently instantiated runs. I can specify which one I want to focus on using the syntax you suggest, but it's not necessary for me. What version of cylc are you running?

2025-01-13 21:30 UTC, hollandjg commented on workflow/README.md
> +To loop through a list of cases, you might use a script like this:
added above

2025-01-14 15:39 UTC, cpaniaguam requested changes
Thanks. One more observation about `get_fullnames.py` -- see the contextual comment. Also, it's not clear to me what its use case is within the framework.

2025-01-14 15:39 UTC, cpaniaguam commented on workflow/example/util/template.py
Thanks for the annotations. Looking at the whole picture, the script's current name, `get_fullnames.py`, is a bit misleading as it doesn't specifically deal with "full names" or any particular kind of data. To make its purpose clearer, I suggest renaming the file to something that better reflects its functionality. Here are a few possible names for inspiration: `get_col_values`, `get_column_values`, `print_column`.

2025-01-14 16:23 UTC, danielmwatkins commented on workflow/README.md
> +cylc tui
I've got cylc 8.2.1:
![image](https://github.com/user-attachments/assets/be68ef01-c147-47ac-bf30-58d2caa59404)

Is there a version listed for cylc anywhere in the IFT-Pipeline anymore? I don't see a place where a cylc is listed in the yaml files--it used to be in the ift-env.yaml file.

In the cylc [docs](https://cylc.github.io/cylc-doc/stable/html/tutorial/runtime/introduction.html#the-cylc-tui) it shows that you need to provide the workflow id for `cylc tui`, but that you don't need to provide it for `cylc gui`. What version of cylc are you running?

2025-01-15 15:33 UTC, hollandjg commented on workflow/example/util/template.py
Done.

2025-01-15 15:48 UTC, hollandjg commented on workflow/README.md
> +cylc tui
I'm running 8.4.0. 

In principle, the workflow should work with any version of cylc 8. I removed the ift-env.yaml at some point; all it included was `cylc-flow` and I think the instructions on the cylc website are more likely to stay up-to-date. I've included a link to those [installation instructions](https://cylc.github.io/cylc-doc/latest/html/installation.html) at the top of the file.

Could we look at what happens when you call `cylc tui` on your machine together? That might help me track down the problem.

2025-01-15 15:58 UTC, cpaniaguam reviewed
lgtm

2025-01-15 16:46 UTC, hollandjg commented on workflow/README.md
> +cylc tui
Added a minimum version for cylc in the README. I've been testing under cylc 8.4, so let's use that as our minimum.

2025-01-15 19:47 UTC, danielmwatkins commented on workflow/README.md
> +
Is there a place where the individual variables in the conf files are explained? For example, it's not obvious what order the values in the bounding box are provided in.

2025-01-17 20:54 UTC, hollandjg commented on workflow/README.md
> +
That's a good point. I've consolidated all of the descriptions of the variables in`meta/rose-meta.conf` and updated the rose-suite.conf file to simplify it accordingly. There are a couple of key descriptive comments in there still, but most have moved out. Does that work better for you?

2025-01-17 20:55 UTC, hollandjg commented on workflow/meta/rose-meta.conf
@danielmwatkins here's the updated file.

2025-01-23 14:02 UTC, danielmwatkins commented on workflow/rose-suite.conf
> +# BBOX: "X1,Y1,X2,Y2"
Should probably note that it's lower left, upper right -- I think we get wonky results if the box is specified upper left lower right instead.

2025-01-23 14:03 UTC, danielmwatkins commented on workflow/meta/rose-meta.conf
This is helpful! Is it linked in the readme?

2025-01-23 16:28 UTC, hollandjg commented on workflow/rose-suite.conf
> +# BBOX: "X1,Y1,X2,Y2"
Good point! I've updated that here and in the metadata file.

2025-01-24 14:42 UTC, hollandjg commented on workflow/meta/rose-meta.conf
It is now.

2025-01-24 15:42 UTC, danielmwatkins submitted a review, later dismissed

2025-01-24 16:02 UTC, hollandjg commented on workflow/README.md
> +cylc vip . --set-file example/hudson-bay.conf -n hudson-bay --run-name=july-2008 --initial-cycle-point=2008-07-13 --final-cycle-point=2008-07-15
```suggestion
cylc vip . --set-file example/hudson-bay.conf -n hudson-bay --run-name=may-2006 --set 'START="2006-05-04"' --set 'END="2006-05-06"'
cylc vip . --set-file example/hudson-bay.conf -n hudson-bay --run-name=july-2008 --set 'START="2008-07-13"' --set 'END="2008-07-15"'
```

2025-01-24 20:10 UTC, merged