Feat update localflow
WilhelmusLab/ice-floe-tracker-pipeline pull request #88
Opened 2023-11-02 18:26 UTC by tdivoll

This updates the local flow.cylc to work from the Docker containers, and hopefully alleviates the ease of use for running locally on simple examples, particularly for fetching data from NASA Worldview and Space-Track APIs.

2023-11-02 19:05 UTC, cpaniaguam requested changes
This is good! Added some comments for readability.

2023-11-03 15:08 UTC, tdivoll commented on README.md
> +   * be sure to replace source, s(startdate), e(enddate), c(crs), and b(bounding box) with your inputs
Fetchdata only has short flags; longer names are used in the script to create the necessary variables so the long names are reserved for that purpose.

2023-11-03 15:15 UTC, tdivoll commented on config/cylc_local/flow.cylc
> +        # Convert param location list to indexable bash array and make directories for each location
`sed` is just tokenizing the string inputs, for as many inputs as there are in the list, which we pipe into a bash array. I added `# sed is used to tokenize the list of comma-separated inputs` to compliment the original comment `# Convert param location list to indexable bash array and make directories for each location`

2023-11-03 16:05 UTC, cpaniaguam commented on README.md
> +3. Update inputs and run the following: ```docker run --env SPACEUSER --env SPACEPSWD --mount type=bind,source=<your_desired_output_dir>,target=/tmp brownccv/icefloetracker-fetchdata:main python3 /us
```suggestion
3. Update inputs and run the following:
```
docker run --env SPACEUSER --env SPACEPSWD --mount type=bind,source=<your_desired_output_dir>,target=/tmp brownccv/icefloetracker-fetchdata:main python3 /usr/local/bin/pass_time_cylc.py --startdate <YYYY-MM-DD> --enddate <YYYY-MM-DD> --csvoutpath /tmp --centroid_x <input_centroid_x> --centroid_y $<input_centroid_y> --SPACEUSER $SPACEUSER --SPACEPSWD $SPACEPSWD
```

2023-11-03 16:09 UTC, cpaniaguam commented on README.md
> +3. Update inputs and run the following: ```docker run --env SPACEUSER --env SPACEPSWD --mount type=bind,source=<your_desired_output_dir>,target=/tmp brownccv/icefloetracker-fetchdata:main python3 /us
The change is not being rendered properly. Each set of triple back ticks should be in a line by itself so the formatting is applied correctly. Like this:
'''
comand # use back ticks instead
'''

2023-11-06 19:59 UTC, merged